#!/bin/bash

# le but de ce programme est de detecter sur quel port usb
# est connecte le capteur de
# temperature associe au ventilo du processeur
# dossierc cible : /sys/class/hwmon
# puis modifier le fichier /etc/fancontrol en consequence

# dossier cible :
ADRR=/sys/class/hwmon/

# fichier de controle
FANCTRL=/etc/fancontrol


val=0
for i in `seq 0 10`; do
	# methode Word + cat
	#	for WORD in `cat /sys/class/hwmon/hwmon$(($i))/temp2_input`
	#	do
	#		echo $WORD;
	#		val=$((WORD));
	#	done
	
	# methode FILE
	FILE=$ADRR"hwmon"$(($i))"/temp2_input"
	if [[ -f "$FILE" ]]; then		# recheche de la position du fichier de température
	#    echo "$FILE exists.";
	    SENSOR=$ADRR"hwmon"$(($i))"/temp2_input"
	    break
	fi

done

echo "sensor found  at "$SENSOR
val=$i

if [[ -f "$FANCTRL" ]]; then	# check if file exist to remove it
	rm /etc/fancontrol
fi


if [[ -f "$FANCTRL" ]]; then	# check if file successfully removed
	echo "/etc/fancontrol not removed, rm did not work : use sudo"
	exit
else
	echo "updating /etc/fancontrol..."

	# Open file descriptor (fd) 3 for read/write on a text file.
	exec 3<> /etc/fancontrol # ? sudo
   
    echo "# Configuration file generated by pwmconfig, changes will be lost" >&3
    echo "INTERVAL=10" >&3
    echo "DEVPATH=hwmon$((val))=devices/platform/nct6775.656" >&3
    echo "DEVNAME=hwmon$((val))=nct6776" >&3
    echo "FCTEMPS= hwmon$((val))/pwm2=hwmon$((val))/temp2_input" >&3
    echo "FCFANS= hwmon$((val))/pwm2=" >&3
    echo "MINTEMP=hwmon$((val))/pwm2=35" >&3
    echo "MAXTEMP=hwmon$((val))/pwm2=70" >&3
    echo "MINSTART=hwmon$((val))/pwm2=90" >&3
    echo "MINSTOP=hwmon$((val))/pwm2=80" >&3
    echo "MINPWM=hwmon$((val))/pwm2=0" >&3
    echo "MAXPWM=hwmon$((val))/pwm2=255" >&3

	# Close fd 3
	exec 3>&-
fi

if [[ -f "$FANCTRL" ]]; then	# check if file successfully created
# check if file lines are correct could be nice
	echo "file updated, restart fancontrol service"
	service fancontrol restart
else
	echo "something get wrong : no fancontrol file !"
fi

HWMON_PATH="/sys/class/hwmon/hwmon$((val))/temp2_input"
# verif :
#echo $HWMON_PATH

# GUI : show path
zenity --warning --title="Sonde CPU" --no-wrap --text="Fichier de la sonde : \n"$HWMON_PATH
